name: Offline PlantID
options:
  bundleIdPrefix: com.kqinami
settings:
  base:
    SWIFT_VERSION: 5.0
    GENERATE_INFOPLIST_FILE: YES
targets:
  Offline PlantID:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
    resources:
      - path: inat_models
