name: Offline PlantID
options:
  bundleIdPrefix: com.kqinami
settings:
  base:
    SWIFT_VERSION: 5.0
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
targets:
  Offline PlantID:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
      - path: inat_models/aiy_plants_V1_labelmap.csv
        type: file
        buildPhase: resources
      - path: inat_models/aiy_plants_common_names.json
        type: file
        buildPhase: resources
      - path: inat_models/inat_plant.tflite
        type: file
        buildPhase: resources
      - path: Resources/LaunchScreen.storyboard
        type: file
        buildPhase: resources
      - path: Resources/Assets.xcassets
        type: file
        buildPhase: resources
